### ISSUE TITLE
Full snapshot fails for large DB size

### ISSUE THREAD

**Issue by nikhilsap** [gardener/etcd-backup-restore#54] opened 2018-09-10 11:38 UTC
We are doing performance test on Etcd.
DB size is of 2GB. 
Connection Timeout : 300 secs
We have configured the full snapshot for every 10 mins. 

The schedule full snapshot was at 10:40:00.
From the log , we can see that at 10.38 ,level=warning msg="watch channel responded with err: %v etcdserver: mvcc: required revision has been compacted. 

![image](https://user-images.githubusercontent.com/41104107/45295340-fd1bc480-b51b-11e8-9240-ac87e61ea365.png)

Still its the same, the full snapshot has not been taken. Even its not taking delta snapshot.
ETCD and API server both are in healthy state. 

When the DB size was 1.5GB, it took the full snapshot properly.

**Comment by swapnilgm** [comment] 2018-09-10 16:07
Closing this issue since this issue is duplicate of https://github.com/gardener/etcd-backup-restore/issues/48 And PR for the fix is under review and will be merged soon.

**Closed by swapnilgm** 2018-09-10 16:07 UTC
Labels: triage/duplicate
